
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: expense-service
          uri: http://localhost:8081
          predicates:
            - Path=/expenses/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
            